### PR TITLE
Improvements Over Backend

### PR DESCRIPTION
**Pull request by mentix02**
Code has been cleaned and formatted according to PEP-8 common conventions. Few other minor changes include - 

- posts will now appear chronologically 
    - was achieved by changing `class Meta` inside of `Backend/post/models.py` by adding the ordering option with items `-published` and `-pk`.
- added a post queried by Author username views for backend and configured urls
    - was achieved by adding a custom `APIView` from djangorestframework by querying slug - `username` as `author__username`
- serializers are easier to work with since `get_methods` for acquiring username of a post model's creator was changed to a string related field with a default of `many=False`. 
- minor optimizations include changing lists to tuples

### CODE REVIEW

**Comment by mentix02** [comment]
- added a post queried by Author username views for backend and configured urls

**Comment by vinitraj10** [comment]
Hello Thanks For making PR, I will merge it once I run it on my system!

**Comment by mentix02** [comment]
Any updates?

**Comment by vinitraj10** [comment]
> Any updates?

Will update soon don't worry 😄

**Comment by vinitraj10** [comment]
Great Work, Thanks For doing it! ❤️

**Pull request merged**
